"""
FinePrint — Lawyer Prep Brief (PDF)

Generates a 1-2 page PDF using ReportLab:
1. Document type, parties, date
2. Top 3-5 clauses at issue (quoted verbatim)
3. Specific questions to ask
4. Documents to bring
5. Footer: generated by automated tool

CRITICAL: Every quoted clause must match the source text exactly.
"""

from __future__ import annotations

import logging
from pathlib import Path

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm, cm
from reportlab.lib.colors import HexColor
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY

logger = logging.getLogger(__name__)

DATA_DIR = Path(__file__).parent.parent.parent / "data"
OUTPUT_DIR = DATA_DIR / "briefs"


def generate_brief_pdf(
    doc_id: str, full_text: str, analysis: dict
) -> Path:
    """
    Generate the Lawyer Prep Brief PDF.

    Args:
        doc_id: Document identifier
        full_text: Full document text
        analysis: Full analysis response dict

    Returns:
        Path to the generated PDF file
    """
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    pdf_path = OUTPUT_DIR / f"lawyer_brief_{doc_id}.pdf"

    doc = SimpleDocTemplate(
        str(pdf_path),
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2.5 * cm,
    )

    styles = _create_styles()
    story = []

    # ─── Header ──────────────────────────────────────────────
    story.append(Paragraph("LAWYER PREP BRIEF", styles["title"]))
    story.append(Spacer(1, 3 * mm))
    story.append(Paragraph(
        "Confidential — For Discussion with Your Legal Advocate",
        styles["subtitle"]
    ))
    story.append(Spacer(1, 2 * mm))
    story.append(HRFlowable(
        width="100%", thickness=1,
        color=HexColor("#334155"), spaceAfter=5 * mm
    ))

    # ─── Section 1: Document Overview ─────────────────────────
    story.append(Paragraph("1. Document Overview", styles["section"]))

    # Try to extract basic info from the document text
    doc_type = _detect_doc_type(full_text)
    parties = _extract_parties(full_text)

    overview_data = [
        ["Document Type:", doc_type],
        ["Parties:", parties],
        ["Document ID:", doc_id],
    ]

    overview_table = Table(overview_data, colWidths=[4 * cm, 12 * cm])
    overview_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
    ]))
    story.append(overview_table)
    story.append(Spacer(1, 5 * mm))

    # ─── Section 2: Clauses at Issue ──────────────────────────
    story.append(Paragraph("2. Clauses at Issue", styles["section"]))
    story.append(Spacer(1, 2 * mm))

    clauses = analysis.get("clauses", [])
    enforceability = analysis.get("enforceability_flags", [])
    baselines = analysis.get("baseline_verdicts", [])

    # Select top 3-5 most important clauses
    flagged_clause_ids = {f.get("clause_id") for f in enforceability}
    unusual_clause_ids = {
        b.get("clause_id") for b in baselines
        if b.get("verdict") in ("stricter_than_usual", "unusual")
    }
    important_ids = flagged_clause_ids | unusual_clause_ids

    # Also include high-risk clauses
    for clause in clauses:
        if clause.get("risk_score", 1) >= 4:
            important_ids.add(clause.get("id"))

    important_clauses = [
        c for c in clauses if c.get("id") in important_ids
    ][:5]  # Max 5

    if not important_clauses:
        # Fallback: top 3 by risk
        sorted_clauses = sorted(
            clauses, key=lambda c: c.get("risk_score", 0), reverse=True
        )
        important_clauses = sorted_clauses[:3]

    for clause in important_clauses:
        clause_heading = clause.get("heading", clause.get("type", "Clause"))
        clause_id = clause.get("id", "")
        risk = clause.get("risk_score", 1)

        # Find verdict and flag for this clause
        verdict_text = ""
        for bv in baselines:
            if bv.get("clause_id") == clause_id:
                v = bv.get("verdict", "").replace("_", " ").title()
                if v and v != "No Baseline":
                    verdict_text = f" | Baseline: {v}"
                break

        flag_text = ""
        for ef in enforceability:
            if ef.get("clause_id") == clause_id:
                status = ef.get("status", "").replace("_", " ").title()
                flag_text = f" | Enforceability: {status}"
                break

        story.append(Paragraph(
            f"<b>{clause_heading} ({clause_id})</b> — Risk: {risk}/5{verdict_text}{flag_text}",
            styles["clause_header"]
        ))

        # Quote the clause verbatim — CRITICAL: must match source
        clause_text = clause.get("text", "")
        # Truncate very long clauses for the brief
        if len(clause_text) > 500:
            clause_text = clause_text[:497] + "..."

        story.append(Paragraph(
            f"<i>\"{clause_text}\"</i>",
            styles["quote"]
        ))
        story.append(Spacer(1, 3 * mm))

    # ─── Section 3: Questions to Ask ──────────────────────────
    story.append(Paragraph("3. Specific Questions to Ask Your Lawyer", styles["section"]))
    story.append(Spacer(1, 2 * mm))

    questions = _generate_questions(important_clauses, enforceability, baselines)
    for q in questions:
        story.append(Paragraph(f"• {q}", styles["bullet"]))
    story.append(Spacer(1, 5 * mm))

    # ─── Section 4: Documents to Bring ─────────────────────────
    story.append(Paragraph("4. Documents to Bring", styles["section"]))
    story.append(Spacer(1, 2 * mm))

    docs_to_bring = [
        "The original offer letter / agreement (this document)",
        "Any previous correspondence with the employer regarding terms",
        "Your resume and the job description for the role",
        "Details of any training programs mentioned in the agreement",
        "Your previous employment agreement (for comparison)",
        "Any written communications about the terms you wish to discuss",
    ]
    for d in docs_to_bring:
        story.append(Paragraph(f"• {d}", styles["bullet"]))

    # ─── Footer ──────────────────────────────────────────────
    story.append(Spacer(1, 10 * mm))
    story.append(HRFlowable(
        width="100%", thickness=0.5,
        color=HexColor("#94a3b8"), spaceBefore=5 * mm
    ))
    story.append(Paragraph(
        "<i>This brief was generated by an automated tool (FinePrint) "
        "for discussion with your legal advocate. It is not legal advice. "
        "All quoted clauses are reproduced verbatim from the source document.</i>",
        styles["footer"]
    ))

    # Build PDF
    doc.build(story)
    logger.info(f"Generated lawyer brief PDF: {pdf_path}")
    return pdf_path


def _create_styles() -> dict:
    """Create custom paragraph styles for the brief."""
    base = getSampleStyleSheet()

    return {
        "title": ParagraphStyle(
            "BriefTitle",
            parent=base["Title"],
            fontSize=16,
            fontName="Helvetica-Bold",
            textColor=HexColor("#1e293b"),
            alignment=TA_CENTER,
            spaceAfter=2 * mm,
        ),
        "subtitle": ParagraphStyle(
            "BriefSubtitle",
            parent=base["Normal"],
            fontSize=9,
            fontName="Helvetica-Oblique",
            textColor=HexColor("#64748b"),
            alignment=TA_CENTER,
        ),
        "section": ParagraphStyle(
            "BriefSection",
            parent=base["Heading2"],
            fontSize=12,
            fontName="Helvetica-Bold",
            textColor=HexColor("#1e293b"),
            spaceBefore=5 * mm,
            spaceAfter=2 * mm,
        ),
        "clause_header": ParagraphStyle(
            "ClauseHeader",
            parent=base["Normal"],
            fontSize=9,
            fontName="Helvetica-Bold",
            textColor=HexColor("#334155"),
            spaceBefore=2 * mm,
        ),
        "quote": ParagraphStyle(
            "ClauseQuote",
            parent=base["Normal"],
            fontSize=8,
            fontName="Helvetica-Oblique",
            textColor=HexColor("#475569"),
            leftIndent=10 * mm,
            rightIndent=5 * mm,
            alignment=TA_JUSTIFY,
            spaceBefore=1 * mm,
            spaceAfter=2 * mm,
        ),
        "bullet": ParagraphStyle(
            "BulletItem",
            parent=base["Normal"],
            fontSize=9,
            fontName="Helvetica",
            leftIndent=8 * mm,
            spaceBefore=1 * mm,
        ),
        "footer": ParagraphStyle(
            "BriefFooter",
            parent=base["Normal"],
            fontSize=7,
            fontName="Helvetica-Oblique",
            textColor=HexColor("#94a3b8"),
            alignment=TA_CENTER,
        ),
    }


def _detect_doc_type(full_text: str) -> str:
    """Detect document type from text."""
    text_lower = full_text.lower()
    if "offer letter" in text_lower or "employment offer" in text_lower:
        return "Employment Offer Letter"
    if "training bond" in text_lower or "service bond" in text_lower:
        return "Training / Service Bond Agreement"
    if "rental" in text_lower or "lease" in text_lower:
        return "Rental / Lease Agreement"
    if "employment agreement" in text_lower:
        return "Employment Agreement"
    return "Legal Agreement"


def _extract_parties(full_text: str) -> str:
    """Try to extract party names from document text."""
    # Simple heuristic — look for common patterns
    import re

    patterns = [
        r"between\s+(.+?)\s+(?:and|&)\s+(.+?)(?:\.|,|\n)",
        r"(?:Company|Employer):\s*(.+?)(?:\n|,)",
        r"(?:Employee|Candidate):\s*(.+?)(?:\n|,)",
    ]

    parties = []
    for pattern in patterns:
        match = re.search(pattern, full_text[:2000], re.IGNORECASE)
        if match:
            for group in match.groups():
                cleaned = group.strip()[:60]
                if cleaned:
                    parties.append(cleaned)
            break

    return " and ".join(parties) if parties else "Not explicitly identified in document header"


def _generate_questions(
    clauses: list[dict],
    enforceability: list[dict],
    baselines: list[dict],
) -> list[str]:
    """Generate specific questions based on flagged clauses."""
    questions = []

    flag_map = {f.get("clause_id"): f for f in enforceability}
    verdict_map = {b.get("clause_id"): b for b in baselines}

    for clause in clauses:
        clause_id = clause.get("id")
        clause_type = clause.get("type", "")
        heading = clause.get("heading", clause_type.replace("_", " "))

        flag = flag_map.get(clause_id)
        if flag:
            # Add ask_a_lawyer questions from the flag
            for q in flag.get("ask_a_lawyer", [])[:2]:
                questions.append(q)

        verdict = verdict_map.get(clause_id)
        if verdict and verdict.get("verdict") in ("stricter_than_usual", "unusual"):
            questions.append(
                f"Is the {heading} clause enforceable as written, "
                f"and what are the practical risks of challenging it?"
            )

    # Add general questions
    questions.extend([
        "Are there any additional protections available under state-specific employment legislation?",
        "What would be the cost and timeline if any of these clauses were challenged?",
    ])

    return questions[:8]  # Max 8 questions
